export const serviceCategories = [
  "All Services",
  "Air & Water",
  "Furniture & Floors",
  "Property Cleaning",
] as const;

export type ServiceCategory = Exclude<(typeof serviceCategories)[number], "All Services">;

const categorySlugs: Record<ServiceCategory, string> = {
  "Air & Water": "air-water",
  "Furniture & Floors": "furniture-floors",
  "Property Cleaning": "property-cleaning",
};

export function categoryFromSlug(slug: string | undefined): ServiceCategory | undefined {
  return (Object.keys(categorySlugs) as ServiceCategory[]).find((category) => categorySlugs[category] === slug);
}


export type ServicePackage = {
  name: string;
  note: string;
  price?: string;
  image?: string;
};

export type ComparisonRow = {
  label: string;
  values: string[];
};

export type Service = {
  slug: string;
  name: string;
  shortName: string;
  category: ServiceCategory;
  summary: string;
  cardCopy: string;
  icon: string;
  image: string;
  priceNote: string;
  quoteOnly: boolean;
  heroHeading?: string;
  secondaryHeroCta?: { label: string; href: string };
  trustPoints?: string[];
  concerns: string[];
  limitations?: string;
  quotationFactors?: string[];
  inclusions: string[];
  exclusions?: string[];
  steps: string[];
  preparation: string;
  duration: string;
  packages?: ServicePackage[];
  optionsHeading?: string;
  optionsNote?: string;
  optionsCtaLabel?: string;
  packageCtaLabel?: string;
  noFeaturedOption?: boolean;
  comparisonRows?: ComparisonRow[];
  seoTitle?: string;
  seoDescription?: string;
  faqs: Array<{ question: string; answer: string }>;
};

const sharedFaq = {
  question: "When is my appointment confirmed?",
  answer:
    "Your request is provisional until Endeavor confirms the price, team availability, property access and the requested time.",
};

export const services: Service[] = [
  {
    slug: "ac-cleaning",
    name: "AC Cleaning",
    shortName: "AC Cleaning",
    category: "Air & Water",
    heroHeading: "Professional AC Cleaning Services in Dubai",
    summary: "Cleaner AC components can support better airflow, fresher indoor spaces and more efficient cooling. Choose the level of cleaning that matches your AC system’s condition and your property’s needs.",
    cardCopy: "Clear service levels for vents, filters and deeper internal AC care.",
    icon: "/assets/ac.webp",
    image: "/assets/service-ac-cleaning.jpg",
    priceNote: "Starting from AED 150 per AC unit",
    quoteOnly: false,
    trustPoints: [
      "Four options",
      "Clear per-unit pricing",
      "Professional equipment",
      "Residential and commercial properties",
      "Dubai-wide service",
    ],
    concerns: [
      "Dust around vents",
      "Dirty filters",
      "Musty odours",
      "Recurring dust",
      "Reduced or uneven airflow",
      "Visible coil buildup",
      "Long periods without cleaning",
      "Renovation dust",
    ],
    limitations: "Cleaning may remove buildup and support airflow through cleaned components. It does not repair refrigerant problems, damaged parts, leaks, electrical faults or other mechanical defects.",
    inclusions: [
      "A pre-service review of the selected AC unit",
      "Cleaning tasks listed in the confirmed option",
      "Protection of the immediate work area",
      "A clear handover when the selected work is complete",
    ],
    steps: [
      "Arrival and option confirmation",
      "Accessible-component inspection",
      "Protection of nearby property",
      "Cleaning of confirmed components",
      "Reinstallation and final check",
      "Handover with photographs where applicable",
    ],
    preparation: "Confirm the unit count and locations, provide access to grills and panels, move fragile items, disclose high ceilings or access restrictions and known faults, arrange building access and parking, and keep children and pets away during the visit.",
    duration: "Duration depends on the option, unit count, AC type, accessibility and buildup. Confirm duration during booking.",
    packages: [
      {
        name: "Pure Flow — Grill and Filter Cleaning",
        price: "AED 150 per unit",
        note: "Routine cleaning of accessible AC grills and washable filters. Recommended for light visible dust, regularly maintained systems and customers who do not require duct or coil cleaning.",
      },
      {
        name: "Fresh Air — AC Duct Cleaning",
        price: "AED 450 per unit",
        note: "Cleaning of grills, washable filters and accessible duct sections. Recommended when dust returns quickly, buildup is visible around vents or duct cleaning has not been completed recently. Duct disinfection is included only when confirmed under the approved method.",
      },
      {
        name: "Coil Care — AC Coil Cleaning",
        price: "AED 500 per unit",
        note: "A standalone service focused on safely cleaning an accessible AC coil. Recommended for visible coil buildup or when coil cleaning is required without duct cleaning.",
      },
      {
        name: "Full AC Cleaning With Coil",
        price: "AED 700 per unit",
        note: "Endeavor’s most comprehensive AC cleaning option, combining accessible duct cleaning, coil cleaning, grills, washable filters and other approved internal components.",
      },
    ],
    comparisonRows: [
      { label: "Price per unit", values: ["AED 150", "AED 450", "AED 500", "AED 700"] },
      { label: "Grills and washable filters", values: ["Included", "Included", "Not included", "Included"] },
      { label: "Accessible ducts", values: ["Not included", "Included", "Not included", "Included"] },
      { label: "Coil", values: ["Not included", "Not included", "Included", "Included"] },
      { label: "Photographs", values: ["Where applicable", "Where applicable", "Where applicable", "Where applicable"] },
    ],
    seoTitle: "AC Cleaning Services in Dubai | Options From AED 150 | Endeavor",
    seoDescription: "Choose from four professional AC cleaning options in Dubai, including grill and filter, duct, coil-only and full AC cleaning. View options and prices before booking.",
    faqs: [
      { question: "Which AC package should I choose?", answer: "Pure Flow suits light visible dust and regularly maintained systems. Fresh Air adds duct cleaning if dust keeps returning quickly. Coil Care targets visible coil buildup on its own. Full AC Cleaning With Coil combines ducts, coil, grills and filters for the most complete clean." },
      { question: "Is the price per property or per unit?", answer: "AC cleaning is priced per unit. The confirmed quote will state the option, quantity, VAT status and any access-related charge." },
      sharedFaq,
    ],
  },
  {
    slug: "water-tank-cleaning",
    name: "Water Tank Cleaning",
    shortName: "Water Tank",
    category: "Air & Water",
    heroHeading: "Professional Water Tank Cleaning in Dubai",
    summary: "Remove accumulated sediment, dirt and residue from your water-storage tank with professional cleaning and disinfection for residential and commercial properties.",
    cardCopy: "Tank care arranged around capacity, property type and access conditions.",
    icon: "/assets/water.webp",
    image: "/assets/service-water-tank.jpg",
    priceNote: "Starting from AED 450",
    quoteOnly: false,
    concerns: [
      "Visible sediment",
      "Cloudy or discoloured water",
      "Unusual taste or odour",
      "Residue around the opening",
      "Sludge or debris",
      "Insects",
      "A damaged cover",
      "An extended period without cleaning",
      "Recent plumbing work",
      "A change of occupancy",
    ],
    limitations: "The service improves storage-tank cleanliness and can remove accumulated debris. It does not certify drinking-water quality. Laboratory testing is required to confirm chemical or microbiological water quality.",
    inclusions: [
      "Capacity and access confirmation",
      "Initial inspection",
      "Isolation where possible",
      "Safe draining",
      "Sediment and sludge removal",
      "Manual scrubbing of accessible walls and floors",
      "Rinsing",
      "Application of an approved disinfectant",
      "Tank-cover cleaning",
      "Final inspection",
      "Photographs where practical",
      "Work-area cleaning",
      "Coordination for return to service",
    ],
    exclusions: [
      "Laboratory testing",
      "Plumbing, pump or float-valve repairs",
      "Tank replacement",
      "Crack sealing, waterproofing or coating",
      "Pipeline cleaning or disinfection",
      "Filter replacement",
      "Inaccessible contamination",
      "Specialist confined-space entry",
      "Scaffolding or cranes",
      "Unusual waste disposal",
      "Refill-water charges",
      "Additional unbooked tanks",
    ],
    steps: [
      "Confirmation and inspection",
      "Isolation and draining",
      "Sediment removal",
      "Internal scrubbing",
      "Rinsing and disinfection",
      "Final inspection and photographs",
      "Preparation for refilling and handover",
    ],
    preparation: "Confirm the tank count and capacity, provide label and access photographs, identify the tank location and drainage point, arrange building approval, parking and permits, inform occupants of the water interruption, stop automatic refill when instructed, disclose leaks or damage and keep people away from the work area. Customers must not enter the tank.",
    duration: "Duration depends on tank size, count, type, stored-water volume, condition, drainage and access.",
    packages: [
      {
        name: "Small",
        price: "AED 450",
        note: "Up to 500 USG — suited to apartments and small residential tanks. Removes accessible sediment, sludge, dirt and residue and disinfects accessible internal surfaces.",
      },
      {
        name: "Medium",
        price: "AED 750",
        note: "550–1,000 USG — suited to villas and medium residential tanks. Removes accessible sediment, sludge, dirt and residue and disinfects accessible internal surfaces.",
      },
      {
        name: "Large",
        price: "AED 1,100",
        note: "1,100–4,000 USG — suited to large villas and buildings. Removes accessible sediment, sludge, dirt and residue and disinfects accessible internal surfaces.",
      },
      {
        name: "Extra Large",
        price: "AED 1,300",
        note: "4,100–10,000 USG — suited to buildings, commercial sites and facilities. Removes accessible sediment, sludge, dirt and residue and disinfects accessible internal surfaces.",
      },
    ],
    optionsNote: "Final pricing can change for multiple tanks, restricted access, heavy contamination, unusual construction, specialist equipment or extra work.",
    optionsCtaLabel: "View Service Options",
    seoTitle: "Water Tank Cleaning Dubai | From AED 450 | Endeavor",
    seoDescription: "Professional water tank cleaning and disinfection in Dubai for tanks up to 10,000 USG. Prices start from AED 450. Request a booking today.",
    faqs: [
      { question: "Which tank-size option should I choose?", answer: "Choose the option that matches your tank's capacity in US gallons (USG): Small (up to 500), Medium (550–1,000), Large (1,100–4,000) or Extra Large (4,100–10,000). Share your tank label or capacity if you're unsure." },
      { question: "Can I send tank photographs?", answer: "Yes. Start the request and continue on WhatsApp to attach photographs that help the team confirm access and scope." },
      sharedFaq,
    ],
  },
  {
    slug: "specialized-deep-cleaning",
    name: "Specialized Deep Cleaning",
    shortName: "Deep Cleaning",
    category: "Property Cleaning",
    heroHeading: "Specialized Deep Cleaning Services in Dubai",
    summary: "Give your property a detailed clean that reaches the surfaces and areas routine cleaning often misses. Select the option that matches the property size, furnishing and condition.",
    cardCopy: "A room-by-room reset built around your property and priorities.",
    icon: "/assets/deep-clean.webp",
    image: "/assets/popular-deep-cleaning.jpg",
    priceNote: "Apartment prices from AED 700. Villas and non-standard conditions require assessment.",
    quoteOnly: false,
    secondaryHeroCta: { label: "Request a Villa Assessment", href: "/book?service=specialized-deep-cleaning&mode=quote" },
    concerns: [
      "Properties needing more than routine cleaning",
      "Occupied or vacant apartments",
      "Accumulated dust and grease",
      "Cleaning before guests or important events",
      "Periodic detailed cleaning",
      "Areas that have not been cleaned recently",
    ],
    limitations: "Inside appliances, inside cabinets, high-level areas, external windows, upholstery, mattresses and specialist stain treatment must be expressly selected or quoted.",
    inclusions: [
      "Dusting and wiping accessible surfaces",
      "Floors and skirting",
      "Doors, frames, switches and handles",
      "Accessible cupboards and wardrobes when empty",
      "Kitchen worktops, cabinet exteriors, sink and accessible appliance exteriors",
      "Bathroom fixtures, tiles and glass",
      "Accessible internal windows",
      "Balconies where confirmed",
      "Removal of ordinary loose dirt",
      "Final work-area check",
    ],
    exclusions: [
      "Post-construction residue",
      "Paint, cement, adhesive or silicone removal",
      "Pest treatment",
      "Hazardous or biological waste",
      "Mould remediation",
      "Repairs",
      "Moving heavy furniture",
      "Inaccessible exterior glass",
      "Façade access",
      "Permanent stain removal",
      "Restoration of damaged surfaces",
    ],
    steps: [
      "Scope confirmation",
      "Condition inspection and photographs",
      "Protection and work sequencing",
      "Room-by-room cleaning",
      "Supervisor check",
      "Customer handover",
    ],
    preparation: "Confirm the furnishing status and apartment size, identify priority areas, send photographs for heavy conditions, remove personal items and valuables, empty cabinets if interiors are included, provide water and electricity, arrange access, parking and permits, and secure pets.",
    duration: "Studio or 1-bedroom apartments normally take 4–5 hours with two technicians; 2–3 bedroom apartments normally take 6–8 hours with three technicians, subject to condition.",
    packages: [
      { name: "Studio — Unfurnished", price: "AED 700", note: "Standard deep-cleaning scope for a studio apartment in confirmed standard condition, unfurnished." },
      { name: "Studio — Furnished", price: "AED 900", note: "Standard deep-cleaning scope for a studio apartment in confirmed standard condition, furnished." },
      { name: "1 Bedroom — Unfurnished", price: "AED 900", note: "Standard deep-cleaning scope for a 1-bedroom apartment in confirmed standard condition, unfurnished." },
      { name: "1 Bedroom — Furnished", price: "AED 950", note: "Standard deep-cleaning scope for a 1-bedroom apartment in confirmed standard condition, furnished." },
      { name: "2 Bedroom — Unfurnished", price: "AED 1,600", note: "Standard deep-cleaning scope for a 2-bedroom apartment in confirmed standard condition, unfurnished." },
      { name: "2 Bedroom — Furnished", price: "AED 1,850", note: "Standard deep-cleaning scope for a 2-bedroom apartment in confirmed standard condition, furnished." },
      { name: "3 Bedroom — Unfurnished", price: "AED 2,100", note: "Standard deep-cleaning scope for a 3-bedroom apartment in confirmed standard condition, unfurnished." },
      { name: "3 Bedroom — Furnished", price: "AED 2,150", note: "Standard deep-cleaning scope for a 3-bedroom apartment in confirmed standard condition, furnished." },
    ],
    optionsNote: "Prices apply only to apartments in standard deep-cleaning condition and the confirmed standard scope. Villas, properties above three bedrooms, post-construction conditions, heavy grease, pest contamination and unusual residue require photographs, assessment and quotation.",
    optionsCtaLabel: "View Apartment Options",
    seoTitle: "Specialized Deep Cleaning Dubai | Apartment Prices | Endeavor",
    seoDescription: "Detailed furnished and unfurnished apartment deep cleaning in Dubai. View standard apartment prices or request a villa assessment.",
    faqs: [
      { question: "What if I have a villa or a property above three bedrooms?", answer: "Request a Villa Assessment. Villas, properties above three bedrooms and non-standard conditions are quoted after photographs and an assessment." },
      { question: "Are appliance and cabinet interiors included?", answer: "No. Inside appliances, inside cabinets, high-level areas, external windows, upholstery, mattresses and specialist stain treatment must be expressly selected or quoted." },
      sharedFaq,
    ],
  },
  {
    slug: "external-window-facade-cleaning",
    name: "External Window & Façade Cleaning",
    shortName: "Window & Façade",
    category: "Property Cleaning",
    heroHeading: "External Window & Façade Cleaning in Dubai",
    summary: "Improve the appearance of exterior glass and accessible building surfaces with a cleaning plan based on the property, height, access method and surface condition.",
    cardCopy: "Clearer exterior surfaces with access requirements reviewed first.",
    icon: "/assets/inspection.webp",
    image: "/assets/service-window-facade.jpg",
    priceNote: "Site assessment and quotation",
    quoteOnly: true,
    concerns: [
      "Villas and townhouses",
      "Low-rise buildings",
      "Shops and offices",
      "Managed properties",
      "Exterior glass with dust or water marks",
      "Façade surfaces requiring planned cleaning",
      "One-time or periodic projects",
    ],
    limitations: "No price is shown until the access method and scope are approved.",
    quotationFactors: [
      "Building type and height",
      "Glass or façade area",
      "Surface material",
      "Level of soil and staining",
      "Safe access from inside or outside",
      "Ladders, platforms, rope access, scaffolding or lifting equipment",
      "Water access",
      "Permits and building-management approval",
      "Operating hours",
      "Parking, traffic or pedestrian control",
    ],
    inclusions: [
      "Site and access review",
      "Confirmation of surfaces",
      "Protection of the immediate area",
      "Removal of loose dust",
      "Washing of accessible exterior glass or approved façade surfaces",
      "Cleaning of frames and sills when quoted",
      "Spot check",
      "Work-area cleanup",
      "Photographs where practical",
    ],
    exclusions: [
      "Rope access, scaffolding, cranes or lifting equipment unless quoted",
      "Sealant or façade repair",
      "Scratch removal",
      "Glass restoration",
      "Paint, cement or adhesive removal unless assessed",
      "Work near unsafe electrical or structural conditions",
      "Unrestricted access to neighbouring property",
      "Permanent mineral etching",
      "Interior window cleaning unless included",
    ],
    steps: [
      "Photo review",
      "Site assessment",
      "Access and safety plan",
      "Quotation approval",
      "Area protection",
      "Cleaning",
      "Quality check",
      "Handover",
    ],
    preparation: "Provide building and elevation photographs, the approximate height and number of windows, arrange authorised access and permits, identify water and power availability, disclose restricted areas, advise occupants and remove items from balconies and window areas.",
    duration: "Duration is project-specific and confirmed after the site assessment.",
    packages: [
      { name: "Accessible Exterior Windows", note: "Cleaning of exterior windows that can be safely reached from inside or with standard access, without specialist equipment." },
      { name: "Villa Windows and Glass", note: "Exterior window and glass cleaning planned around villa height, layout and accessible surfaces." },
      { name: "Low-Rise Façade Cleaning", note: "Façade cleaning for low-rise buildings, assessed for surface material, soil level and safe access." },
      { name: "Commercial or High-Access Façade Projects", note: "Larger or higher-access façade projects assessed for building height, access method, permits and safety requirements." },
    ],
    optionsHeading: "Choose the type of access your property needs",
    optionsNote: "Each option opens a side panel explaining access requirements. No price is shown until the access method and scope are approved.",
    optionsCtaLabel: "Request an Assessment",
    packageCtaLabel: "Request Assessment",
    noFeaturedOption: true,
    seoTitle: "External Window and Facade Cleaning Dubai | Endeavor",
    seoDescription: "Professional external window and facade cleaning in Dubai. Request a site assessment and quotation based on height, access and surface condition.",
    faqs: [
      { question: "Why isn't a fixed price shown?", answer: "Pricing depends on building height, access method, surface area and safety requirements. No price is shown until the access method and scope are approved after assessment." },
      { question: "What if my building needs rope access, scaffolding or a lift?", answer: "Specialist access equipment is only included when it has been assessed and quoted. Share your building height and access details so this can be reviewed." },
      sharedFaq,
    ],
  },
  {
    slug: "sofa-cleaning",
    name: "Sofa Cleaning",
    shortName: "Sofa Cleaning",
    category: "Furniture & Floors",
    heroHeading: "Professional Sofa Cleaning in Dubai",
    summary: "Refresh upholstered seating by removing accessible dust, everyday dirt and treatable marks using a method selected for the fabric and condition.",
    cardCopy: "Focused upholstery care for everyday marks and embedded buildup.",
    icon: "/assets/sofa.webp",
    image: "/assets/service-sofa.jpg",
    priceNote: "Prices from AED 100",
    quoteOnly: false,
    secondaryHeroCta: {
      label: "Send Photos on WhatsApp",
      href: "https://wa.me/971588754060?text=Hello%20Endeavor%2C%20I%20have%20photos%20of%20my%20sofa%20for%20a%20cleaning%20quote.",
    },
    concerns: [
      "Accumulated dust",
      "Everyday dirt",
      "Food or drink marks",
      "Pet hair",
      "Mild odours",
      "Periodic upholstery care",
      "Refreshing furniture before guests or after moving",
    ],
    limitations: "Results depend on the material, age, previous treatment and stain type.",
    inclusions: [
      "Photo and fabric review",
      "Inspection and colourfastness check where appropriate",
      "Dry removal of loose dust and debris",
      "Treatment using the confirmed upholstery method",
      "Attention to accessible seating, back and arms",
      "Cleaning of removable cushions when included",
      "Extraction or controlled drying where appropriate",
      "Final inspection",
    ],
    exclusions: [
      "Fabric repair",
      "Reupholstery",
      "Structural repair",
      "Removal of permanent stains, dye transfer, fading, burns or damage",
      "Guaranteed odour removal",
      "Specialist leather restoration",
      "Pest treatment",
      "Biological or hazardous contamination unless separately assessed",
    ],
    steps: [
      "Confirmation",
      "Inspection",
      "Testing",
      "Property protection",
      "Cleaning",
      "Extraction or rinsing as appropriate",
      "Final check",
      "Drying guidance",
    ],
    preparation: "Send full-sofa and close-up photographs, confirm the number of seats or pieces and material, remove personal items, provide access and ventilation, disclose previous treatments or delicate fabric, and keep children and pets away until advised.",
    duration: "Duration and drying time depend on sofa size, fabric, method, ventilation and condition.",
    packages: [
      { name: "1 Seat", price: "AED 100", note: "Standard cleaning for a single-seat sofa or armchair in typical condition." },
      { name: "2 Seats", price: "AED 200", note: "Standard cleaning for a 2-seat sofa in typical condition." },
      { name: "3 Seats", price: "AED 300", note: "Standard cleaning for a 3-seat sofa in typical condition." },
    ],
    optionsNote: "L-shaped sofas, recliners, sofa beds, loose cushions, unusual materials and more than three seats require photographs and confirmation. Prices are conditional on fabric, pieces, condition and forecast service time.",
    optionsCtaLabel: "View Sofa Options",
    seoTitle: "Sofa Cleaning Dubai | Prices From AED 100 | Endeavor",
    seoDescription: "Professional sofa cleaning in Dubai for upholstered seating. View per-seat prices and send photographs for service confirmation.",
    faqs: [
      { question: "What if I have an L-shaped sofa, recliner or sofa bed?", answer: "Send photographs so the team can confirm the price. L-shaped sofas, recliners, sofa beds, loose cushions, unusual materials and sofas with more than three seats require confirmation before booking." },
      { question: "Can you remove all stains and odours?", answer: "Results depend on the material, age, previous treatment and stain type. Guaranteed removal of permanent stains, dye transfer, fading, burns or odours cannot be promised." },
      sharedFaq,
    ],
  },
  {
    slug: "mattress-cleaning",
    name: "Mattress Cleaning",
    shortName: "Mattress Cleaning",
    category: "Furniture & Floors",
    heroHeading: "Professional Mattress Cleaning in Dubai",
    summary: "Deep-clean mattresses to reduce accumulated dust, everyday dirt and treatable marks, using a method suitable for the mattress material and condition.",
    cardCopy: "Detailed mattress care with the method confirmed before work begins.",
    icon: "/assets/mattress.webp",
    image: "/assets/service-mattress.jpg",
    priceNote: "Prices from AED 150",
    quoteOnly: false,
    secondaryHeroCta: { label: "Book Mattress Cleaning", href: "/book?service=mattress-cleaning&mode=booking" },
    concerns: [
      "Periodic mattress hygiene",
      "Accumulated dust",
      "Everyday dirt",
      "Mild odours",
      "Visible treatable marks",
      "Mattresses used by children or pets",
      "Move-in cleaning",
      "Guest-room preparation",
    ],
    limitations: "Results depend on the stain type, age, material and previous treatment.",
    inclusions: [
      "Condition inspection",
      "Dry removal of loose dust and debris",
      "Cleaning using the approved mattress method",
      "Treatment of disclosed areas where suitable",
      "Extraction or controlled moisture removal where applicable",
      "Final inspection",
      "Drying and use guidance",
    ],
    exclusions: [
      "Mattress repair",
      "Removal of permanent stains, dye, burns, discolouration or damage",
      "Guaranteed odour removal",
      "Bedbug or pest treatment",
      "Hazardous or biological contamination unless separately assessed",
      "Cleaning of the bed frame, pillows or linen unless quoted",
    ],
    steps: [
      "Confirmation",
      "Inspection and suitability check",
      "Surrounding-area protection",
      "Cleaning",
      "Final check",
      "Drying instructions",
    ],
    preparation: "Remove linen and mattress protectors, make both sides accessible if included, send photographs of stains or damage, disclose previous treatment, provide ventilation and access, and keep the mattress unused until sufficiently dry.",
    duration: "Duration and drying time depend on size, method, ventilation, number of mattresses and condition.",
    packages: [
      { name: "Single", price: "AED 150", note: "Standard cleaning for a single mattress in typical condition." },
      { name: "Double", price: "AED 190", note: "Standard cleaning for a double mattress in typical condition." },
      { name: "King", price: "AED 230", note: "Standard cleaning for a king mattress in typical condition." },
    ],
    optionsNote: "Confirm the number of mattresses, exact size, condition and access before booking. Cleaning both sides requires both sides to be accessible and must be confirmed in the scope. Prices are conditional on forecast service time.",
    optionsCtaLabel: "View Mattress Options",
    seoTitle: "Mattress Cleaning Dubai | Prices From AED 150 | Endeavor",
    seoDescription: "Professional mattress cleaning in Dubai for single, double and king mattresses. View prices and request booking confirmation.",
    faqs: [
      { question: "Can both sides of the mattress be cleaned?", answer: "Yes, if both sides are accessible and this is confirmed in the scope before the visit." },
      { question: "Can you remove all stains and odours?", answer: "Results depend on the stain type, age, material and previous treatment. Guaranteed removal of permanent stains, dye, burns, discolouration or odours cannot be promised." },
      sharedFaq,
    ],
  },
  {
    slug: "carpet-cleaning",
    name: "Carpet Shampooing",
    shortName: "Carpet Shampooing",
    category: "Furniture & Floors",
    heroHeading: "Professional Carpet Shampooing in Dubai",
    summary: "Refresh fitted carpets and suitable loose carpets by removing accessible dust, dirt and treatable marks with a cleaning method matched to the material and condition.",
    cardCopy: "A suitable cleaning method for loose rugs and fitted carpet areas.",
    icon: "/assets/deep-clean.webp",
    image: "/assets/popular-carpet-upholstery.jpg",
    priceNote: "Request a quotation",
    quoteOnly: true,
    secondaryHeroCta: {
      label: "Send Photos on WhatsApp",
      href: "https://wa.me/971588754060?text=Hello%20Endeavor%2C%20I%20have%20photos%20of%20my%20carpet%20for%20a%20cleaning%20quote.",
    },
    concerns: [
      "Homes, offices and managed properties",
      "High-traffic areas",
      "Accumulated surface dirt",
      "Food or drink marks",
      "Periodic cleaning",
      "Move-in or move-out preparation",
      "Carpets affected by dust after maintenance work",
    ],
    limitations: "Delicate or valuable rugs may require a specialist service.",
    quotationFactors: [
      "Carpet type and material",
      "Fitted or loose",
      "Total area or dimensions",
      "Number of rooms",
      "Stain type and age",
      "Pile condition",
      "Furniture movement",
      "Access, parking and working hours",
      "Required drying time",
      "Commercial-site requirements",
    ],
    inclusions: [
      "Material and condition inspection",
      "Dry soil removal",
      "Pre-treatment of suitable areas",
      "Shampooing or extraction using the confirmed method",
      "Attention to accessible edges",
      "Controlled rinsing or extraction where applicable",
      "Final inspection",
      "Drying advice",
    ],
    exclusions: [
      "Carpet repair or re-stretching",
      "Moving heavy or fragile furniture unless quoted",
      "Specialist rug restoration",
      "Guaranteed stain or odour removal",
      "Dye correction",
      "Treatment of permanent wear, fading, burns or damage",
      "Pest treatment",
      "Hazardous contamination",
      "Lifting fitted carpet",
    ],
    steps: [
      "Photo and measurement review",
      "Quotation confirmation",
      "Material check",
      "Work-area preparation",
      "Dry soil removal",
      "Cleaning",
      "Final inspection",
      "Ventilation and drying guidance",
    ],
    preparation: "Provide measurements and photographs, identify the material if known, disclose stains and previous treatments, remove small items, agree any furniture movement, ensure ventilation, water and electricity, and keep people and pets off the carpet until dry.",
    duration: "Duration depends on area, method, access and condition.",
    packages: [
      { name: "Fitted Carpet Cleaning", note: "Cleaning for fitted carpet planned around room count, area and material." },
      { name: "Loose Carpet Cleaning", note: "Cleaning for suitable loose carpets and rugs, assessed for material and condition." },
      { name: "Office Carpet Cleaning", note: "Carpet cleaning for commercial and office spaces, planned around access, area and working hours." },
      { name: "Stain-Focused Assessment", note: "A focused assessment of specific stains or marks to confirm the suitable treatment and quotation." },
    ],
    optionsHeading: "Choose the type of carpet cleaning you need",
    optionsNote: "No fixed price is shown until an approved carpet rate is confirmed for your property.",
    optionsCtaLabel: "Request a Quotation",
    packageCtaLabel: "Request Quotation",
    noFeaturedOption: true,
    seoTitle: "Carpet Shampooing Dubai | Home and Office Carpet Cleaning | Endeavor",
    seoDescription: "Professional carpet shampooing in Dubai for homes and offices. Send carpet details and photographs to request a quotation.",
    faqs: [
      { question: "Why isn't a fixed price shown?", answer: "Carpet cleaning is quoted after reviewing the carpet type, area, condition and access. Send measurements and photographs to receive a quotation." },
      { question: "Can you clean delicate or valuable rugs?", answer: "Delicate or valuable rugs may require a specialist service. Disclose the rug type and condition so this can be confirmed before booking." },
      sharedFaq,
    ],
  },
  {
    slug: "marble-polishing",
    name: "Marble Polishing",
    shortName: "Marble Polishing",
    category: "Furniture & Floors",
    heroHeading: "Professional Marble Polishing in Dubai",
    summary: "Restore clarity and improve the appearance of suitable marble surfaces with a polishing plan based on the stone type, area and existing condition.",
    cardCopy: "Condition-led polishing for marble floors and selected surfaces.",
    icon: "/assets/more.webp",
    image: "/assets/service-marble.jpg",
    priceNote: "Site assessment and quotation",
    quoteOnly: true,
    secondaryHeroCta: {
      label: "Send Photos on WhatsApp",
      href: "https://wa.me/971588754060?text=Hello%20Endeavor%2C%20I%20have%20photos%20of%20my%20marble%20floor%20for%20a%20polishing%20quote.",
    },
    concerns: [
      "Dull marble",
      "Light surface scratching",
      "Loss of clarity",
      "Uneven appearance",
      "High-traffic floors",
      "Periodic restoration",
      "Properties preparing for occupancy, handover or presentation",
    ],
    limitations: "Final results depend on the stone condition and previous treatments.",
    quotationFactors: [
      "Stone identification",
      "Area in square metres",
      "Existing finish",
      "Depth of scratches or etching",
      "Stains",
      "Cracks or loose tiles",
      "Access and furniture",
      "Edge work",
      "Required sheen",
      "Commercial operating hours",
      "Protection of adjacent materials",
    ],
    inclusions: [
      "Area and condition inspection",
      "Test area where appropriate",
      "Protection of adjoining surfaces",
      "Cleaning and preparation",
      "Polishing using the confirmed process",
      "Edge attention where accessible and quoted",
      "Residue removal",
      "Final inspection and care guidance",
    ],
    exclusions: [
      "Tile replacement",
      "Crack or joint repair",
      "Levelling or major grinding unless quoted",
      "Stain removal guarantees",
      "Repair of deep etching, chips or structural damage",
      "Polishing of non-marble materials",
      "Sealing unless included",
      "Movement of heavy furniture",
      "Inaccessible edges",
    ],
    steps: [
      "Photo review",
      "Site assessment and measurement",
      "Test and method confirmation",
      "Quotation",
      "Area protection",
      "Staged polishing",
      "Final cleaning",
      "Inspection and handover",
    ],
    preparation: "Provide wide and close-up photographs, the approximate area, disclose previous polishing or coatings, remove movable items, arrange parking and access, and keep the area clear during work and curing or drying.",
    duration: "Duration is project-specific and confirmed after the site assessment.",
    packages: [
      { name: "Residential Marble Floors", note: "Polishing for marble floors in apartments and residential units, assessed for area and condition." },
      { name: "Villa Marble Surfaces", note: "Polishing for villa marble floors and surfaces, assessed for area, access and condition." },
      { name: "Lobby and Commercial Floors", note: "Polishing for lobby and commercial marble floors, planned around operating hours and access." },
      { name: "Focused Area or Room", note: "A focused assessment and polishing plan for a specific area or room." },
    ],
    optionsHeading: "Choose the type of marble polishing you need",
    optionsNote: "No fixed price is shown until a rate and minimum booking value are approved for your property.",
    optionsCtaLabel: "Request an Assessment",
    packageCtaLabel: "Request Assessment",
    noFeaturedOption: true,
    seoTitle: "Marble Polishing Dubai | Floor Assessment and Quotation | Endeavor",
    seoDescription: "Professional marble polishing in Dubai for homes, villas and commercial properties. Request an assessment based on area and stone condition.",
    faqs: [
      { question: "Why isn't a fixed price shown?", answer: "Marble polishing is quoted after a site assessment covering stone type, area, existing finish and condition. A rate and minimum booking value are confirmed before work begins." },
      { question: "Can all marble damage be fully restored?", answer: "Final results depend on the stone condition and previous treatments. Deep etching, chips, cracks and structural damage are not guaranteed to be fully restored." },
      sharedFaq,
    ],
  },
  {
    slug: "post-construction-cleaning",
    name: "Post-Construction Cleaning",
    shortName: "Post-Construction",
    category: "Property Cleaning",
    heroHeading: "Post-Construction Cleaning Services in Dubai",
    summary: "Prepare a newly completed or renovated property for use by removing accessible construction dust and agreed residue through a carefully assessed cleaning plan.",
    cardCopy: "Prepare a newly completed space for inspection, furnishing or handover.",
    icon: "/assets/contract.webp",
    image: "/assets/service-post-construction.jpg",
    priceNote: "Site assessment and quotation",
    quoteOnly: true,
    secondaryHeroCta: {
      label: "Send Project Photos",
      href: "https://wa.me/971588754060?text=Hello%20Endeavor%2C%20I%20have%20project%20photos%20for%20a%20post-construction%20cleaning%20quote.",
    },
    concerns: [
      "New handovers",
      "Renovated rooms or complete properties",
      "Contractor dust",
      "Final cleaning before furniture installation or occupancy",
      "Offices after fit-out",
      "Properties requiring detailed surface-by-surface cleanup",
    ],
    limitations: "Exact inclusions are defined in the quotation.",
    quotationFactors: [
      "Property type and size",
      "Construction completion stage",
      "Dust volume",
      "Paint, cement, grout, adhesive, silicone or protective-film residue",
      "High-level areas",
      "Windows and balconies",
      "Installed fixtures",
      "Water and electricity availability",
      "Waste left by contractors",
      "Access, permits and deadline",
    ],
    inclusions: [
      "Initial condition documentation",
      "Systematic removal of loose construction dust",
      "Wiping of accessible surfaces, doors, frames, switches, skirting and cabinetry",
      "Cleaning of kitchens and bathrooms",
      "Vacuuming and washing floors using suitable methods",
      "Accessible internal glass",
      "Final detailed check",
    ],
    exclusions: [
      "Building or trade work",
      "Removal of heavy rubble or contractor waste unless quoted",
      "Hazardous material",
      "Paint, cement, adhesive or silicone removal without testing and approval",
      "Scratch repair",
      "Polishing or restoration",
      "High external façade work",
      "Repairs",
      "Cleaning before construction is substantially complete",
      "Damage caused by contractors",
    ],
    steps: [
      "Photo or video review",
      "Site inspection",
      "Scope and residue testing",
      "Quotation and schedule",
      "Staged top-to-bottom cleaning",
      "Supervisor inspection",
      "Snag list where appropriate",
      "Customer handover",
    ],
    preparation: "Ensure construction is complete, remove tools and contractor materials, provide safe water and power, arrange access and permits, identify delicate new finishes, provide drawings or area details, disclose the deadline, and keep other trades out of cleaned zones.",
    duration: "Duration and crew size are project-specific.",
    packages: [
      { name: "Apartment After Renovation", note: "Post-renovation cleaning for apartments, assessed for area, residue and completion condition." },
      { name: "Villa After Construction", note: "Post-construction cleaning for villas, assessed for area, residue and completion condition." },
      { name: "Office or Commercial Fit-Out", note: "Cleaning after an office or commercial fit-out, planned around area, access and operating hours." },
      { name: "Focused Renovation-Area Cleanup", note: "A focused cleanup for a specific renovated area or room." },
    ],
    optionsHeading: "Choose the type of post-construction cleaning you need",
    optionsNote: "Pricing remains quotation-based until the scope, area, residue and completion condition are inspected.",
    optionsCtaLabel: "Request an Assessment",
    packageCtaLabel: "Request Assessment",
    noFeaturedOption: true,
    seoTitle: "Post-Construction Cleaning Dubai | Request an Assessment | Endeavor",
    seoDescription: "Detailed post-construction and post-renovation cleaning in Dubai. Request a site assessment and quotation based on property condition and scope.",
    faqs: [
      { question: "Why isn't a fixed price shown?", answer: "Post-construction cleaning is quoted after reviewing the property size, completion stage, residue type and access. Send photos or video to request an assessment." },
      { question: "Does construction need to be finished first?", answer: "Yes. The assessment and quotation assume construction is substantially complete. Cleaning before this stage is not included." },
      sharedFaq,
    ],
  },
  {
    slug: "move-in-move-out-cleaning",
    name: "Move-In / Move-Out Cleaning",
    shortName: "Move-In / Move-Out",
    category: "Property Cleaning",
    heroHeading: "Move-In and Move-Out Cleaning in Dubai",
    summary: "Prepare an empty apartment for arrival or handover with a detailed cleaning scope arranged around your moving deadline.",
    cardCopy: "Prepare a home before arrival or leave it ready for handover.",
    icon: "/assets/more.webp",
    image: "/assets/popular-move-in-out.jpg",
    priceNote: "Apartment prices from AED 700. Villas require assessment and quotation.",
    quoteOnly: false,
    secondaryHeroCta: { label: "Request a Villa Assessment", href: "/book?service=move-in-move-out-cleaning&mode=quote" },
    concerns: [
      "Tenants moving into a vacant apartment",
      "Tenants preparing for handover",
      "Owners preparing a unit for a new occupant",
      "Empty units after ordinary maintenance",
      "Customers working to a confirmed moving date",
    ],
    inclusions: [
      "Dusting and wiping accessible surfaces",
      "Floors and skirting",
      "Doors, frames, switches and handles",
      "Empty cabinet and wardrobe interiors",
      "Kitchen worktops, cabinet surfaces, sink and accessible appliance areas",
      "Bathrooms, tiles, fixtures and glass",
      "Accessible internal windows",
      "Balcony where confirmed",
      "Final room-by-room check",
    ],
    exclusions: [
      "Post-construction cleaning",
      "Heavy paint, cement, adhesive or silicone residue",
      "Exterior high-level glass",
      "Façade work",
      "Furniture or upholstery",
      "Pest treatment",
      "Repair or maintenance",
      "Disposal of tenant belongings or large waste",
      "Permanent stain removal",
      "Utilities or access arrangements",
    ],
    steps: [
      "Property and deadline confirmation",
      "Condition review and photographs",
      "Access and scope confirmation",
      "Room-by-room cleaning",
      "Quality check",
      "Handover",
    ],
    preparation: "Confirm whether it's a move-in or move-out, ensure the property is empty, finish painting and maintenance first, remove belongings and waste, provide water and electricity, arrange keys, permits, parking and lift access, identify the handover deadline, and disclose any construction residue.",
    duration: "Standard apartment duration is approximately 4–8 hours depending on size and condition. Timing is confirmed before booking.",
    packages: [
      { name: "Studio", price: "AED 700", note: "Standard move-in/move-out cleaning for an empty studio apartment in standard condition." },
      { name: "1 Bedroom", price: "AED 900", note: "Standard move-in/move-out cleaning for an empty 1-bedroom apartment in standard condition." },
      { name: "2 Bedroom", price: "AED 1,150", note: "Standard move-in/move-out cleaning for an empty 2-bedroom apartment in standard condition." },
      { name: "3 Bedroom", price: "AED 1,400", note: "Standard move-in/move-out cleaning for an empty 3-bedroom apartment in standard condition." },
    ],
    optionsNote: "Prices apply to empty apartments in standard condition and the confirmed standard scope. Villas, furnished properties, post-construction conditions, heavy residue and non-standard requirements need assessment and quotation.",
    optionsCtaLabel: "View Apartment Prices",
    seoTitle: "Move-In and Move-Out Cleaning Dubai | Endeavor",
    seoDescription: "Detailed move-in and move-out apartment cleaning in Dubai. View standard apartment prices or request a villa assessment.",
    faqs: [
      { question: "What if I have a villa or furnished property?", answer: "Request a Villa Assessment. Villas, furnished properties, post-construction conditions and non-standard requirements are quoted after assessment." },
      { question: "Does the apartment need to be empty?", answer: "Yes, standard apartment prices apply to empty apartments in standard condition. Furnished properties need a separate assessment." },
      sharedFaq,
    ],
  },
  {
    slug: "kitchen-duct-cleaning",
    name: "Kitchen Duct Cleaning",
    shortName: "Kitchen Duct",
    category: "Air & Water",
    summary: "Specialist kitchen-extraction cleaning planned from system type, access, usage and the components included.",
    cardCopy: "A defined cleaning scope for kitchen extraction components and access points.",
    icon: "/assets/pest.webp",
    image: "/assets/service-kitchen-duct.jpg",
    priceNote: "Inspection or system details required for a quote",
    quoteOnly: true,
    concerns: ["Visible grease buildup", "Planned extraction maintenance", "Commercial kitchen scheduling", "Restricted duct access"],
    inclusions: ["System and access review", "A component-specific cleaning scope", "Work scheduled around approved site access", "Completion handover"],
    steps: ["Share system and site details", "Arrange an inspection if needed", "Approve scope and timing", "Complete and document the agreed work"],
    preparation: "Provide extraction-system photographs, kitchen type, operating hours, access points and any site permit requirements.",
    duration: "Duration is confirmed after system size, access and operating constraints are reviewed.",
    faqs: [
      { question: "Can this be scheduled outside operating hours?", answer: "Share the permitted working window. The confirmed quotation will include the agreed schedule." },
      { question: "What components are included?", answer: "Only components listed in the confirmed scope are included. Access work and additional components are stated separately." },
      sharedFaq,
    ],
  },
  {
    slug: "bathroom-deep-cleaning",
    name: "Bathroom Deep Cleaning",
    shortName: "Bathroom Cleaning",
    category: "Property Cleaning",
    summary: "Focused bathroom cleaning for agreed fixtures, surfaces and detailed areas beyond a routine visit.",
    cardCopy: "Detailed attention for the bathroom surfaces and fixtures you identify.",
    icon: "/assets/deep-clean.webp",
    image: "/assets/service-bathroom.jpg",
    priceNote: "Price confirmed by bathroom count and condition",
    quoteOnly: false,
    concerns: ["Detailed fixture cleaning", "Buildup in high-use areas", "A bathroom handover", "Cleaning beyond a routine visit"],
    inclusions: ["Bathroom condition review", "A confirmed fixture and surface checklist", "Detailed cleaning of agreed areas", "Completion walkthrough"],
    steps: ["Share bathroom count and photos", "Confirm the detailed checklist", "Complete the agreed cleaning", "Review the finished areas"],
    preparation: "Remove personal items from counters, showers and tubs, and point out delicate materials or damaged seals.",
    duration: "Duration depends on bathroom count, size and current condition.",
    faqs: [
      { question: "Can I book one bathroom?", answer: "Share the bathroom count and photographs. Endeavor will confirm the available option and price." },
      { question: "Are repair or re-sealing tasks included?", answer: "No repair is assumed. Any separate work must be confirmed before the visit." },
      sharedFaq,
    ],
  },
];

export function getService(slug: string) {
  return services.find((service) => service.slug === slug);
}

export const featuredServices = [
  services[0],
  services[1],
  services[2],
  services[8],
  services[6],
];
